### ISSUE TITLE
[v4.0.3/Magento 2.4.5] Causes "Only X Left" on configurable product page to not show

### ISSUE THREAD

**Issue by FadedOut** [mageplaza/magento-2-lazy-loading#20]
### Preconditions (*)
1. Magento 2.4.5-p1
2. Mageplaza Lazy Loading v4.0.3
3. PHP 8.1

### Steps to reproduce (*)
1. Enable "Only X Left" in Magento settings (Configuration > Catalog > Inventory)
2. Have Mageplaza Lazy Loading module installed and enabled, but don't even need it enabled in the admin configuration

### Expected result (*)
1. For the "Only X Left" to show on the product page, to not be affected by this plugin - why it is not sure. My guess is the "Only X Left" is using some javascript to show [on variable products] and Mageplaza module blocks/conflicts with it.

### Actual result (*)
1. Mageplaza Lazy Loading will block the showing of the "Only X Left" on product page. It simply will not show.

I spent weeks without this feature and not being able to figure out why it was not showing. I had no clue this module would have anything to do with that area of the website. But after much debugging I found that I needed to just have this module completely removed in order for it to not mess with that. Even having it "disabled" in the Admin configuration didn't work. The module needed to be removed from composer.json (and setup:upgrade ran) then the "Only X Left" worked again. Very frustrating. As mentioned above, I'm not sure why this module would affect that area of the product page but it does. 

So anyone else using the feature "Only X Left" for product stock and using this module, be warned v4.0.3 will break this.

**Comment by KhietNguyen83** [comment]
Regarding this issue, please download the extension directly from our site https://www.mageplaza.com/magento-2-lazy-loading/ along with the support package for further inspections and technical support. Thanks a lot!
